### ISSUE TITLE
Issue: I cannot send the message

### ISSUE THREAD

**Issue by Blyxyas** [Fraserbc/BetterDiscord-Embeds#19]
I can't send the message with the embed

**Comment by Dogloverblue** [comment]
Same problem over here

**Comment by Fraserbc** [comment]
Ok, BetterDiscord recently deprecated JQuery which broke my plugin. I've just pushed a commit that should fix this. Can you try redownloading it and trying again

**Comment by Ranger-4297** [comment]
> Ok, BetterDiscord recently deprecated JQuery which broke my plugin. I've just pushed a commit that should fix this. Can you try redownloading it and trying again

Just tried it. Still does not allow you to send the message. I've downloaded it twice. I can't send the normal messages starting with /e

**Comment by Ranger-4297** [comment]
Working. I just didn't understand
